### PR TITLE
Install files into /usr/libexec/bear instead of /usr/libexec

### PR DESCRIPTION
**Pull request by morxa**
As the installed files have rather generic names (e.g., libexec.so), put them
into a sub-directory so it is clear that those files belong to bear.

### CODE REVIEW

**Comment by rizsotto** [comment]
Hi @morxa , thanks for the PR.

Can you give me a context for this? Which packaging guidelines suggest this? Or what problem you might see if we keep it as it is now?

**Comment by rizsotto** [comment]
I'm wondering if you can achieve the same result by passing `CMAKE_INSTALL_LIBEXECDIR` to `cmake`?

**Comment by morxa** [comment]
> Hi @morxa , thanks for the PR.
> 
> Can you give me a context for this? Which packaging guidelines suggest this? Or what problem you might see if we keep it as it is now?

The main problem that I see are potential conflicts and confusion which package a file belongs to, e.g., when I see `/usr/libexec/libexec.so`, I would never guess this is part of bear (I can easily query that information, but it's still confusing) and there is no guarantee that some other package wants to use the same name. If I look on my Fedora installation, most files in `/usr/libexec` are either directories or binaries that have the name of the package prefixed, or have some other way to clarify where it comes from. Also, the [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html) states (emphasis mine):
> /usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. **Applications may use a single subdirectory under /usr/libexec.**

So this is at least a supported use case, if not the intended one.


> I'm wondering if you can achieve the same result by passing `CMAKE_INSTALL_LIBEXECDIR` to `cmake`?

Yes, that would probably work and I've also briefly considered this. I'm not sure if that's the better way, because this is really supposed to be the libexec dir, not some sub-directory. But if you think that's the better approach, that would also work for me.

Side note: I forgot to patch one file, which causes at least one of the build failures. I'll fix it if you intend to merge this PR.

**Comment by rizsotto** [comment]
Hey @morxa ,

Thanks for coming back and give the detailed explanation. I really appreciate it. I was thinking about this change...

- I'm planing to merge the `er` and `wrapper` executables into a single one. (Most probably named as `wrapper`.) These shall be out of the regular `PATH` but they are executables. Can live in `/usr/libexec/bear` directory or anywhere else.
- The `libexec.so` is a different beast. It's a shared library, which I don't want anybody to link against it.
  - But there is a ticket to make it work on multilib environment (when it works against 32 bit and 64 bit tools). For that I will need to create two shared libs. And install them as `/usr/lib` (for the 32 bit) and `/usr/lib64` (for the 64 bit) and the `LD_PRELOAD` value will be `/usr/$LIB`. (See [this](https://github.com/rizsotto/Bear/tree/2.4.4#build-with-multiple-architecture-support) for more.)
  - All these means the `libexec.so` shall be either `/usr/libexec/bear/lib64/libexec.so` and `/usr/libexec/bear/lib/libexec.so` or just fall back to the `/usr/lib64/libexec.so` and `/usr/lib/libexec.so`.

I'm pretty much convinced that putting these files under an extra `bear` directory is useful. The question is how we do it. Shall the upstream dictate how packages shall be made? I tried to be flexible in the past (means not force things) and let packagers override locations.

- So, I would recommend to introduce a variable `PRIVATE_INSTALLDIR` which can have the value `${CMAKE_INSTALL_LIBEXECDIR}/bear`. And use that all around where it need to refer the install location. This can be overridden by packagers if needed.
- For `libexec.so` try to introduce the `lib/lib64` directories inside the `PRIVATE_INSTALLDIR`. (Make sure these are not hardcoded, because Debian system has a different convention `lib/i386-linux-gnu` and `lib/x86_64-linux-gnu`)
- `config.h.in` shall have `LIBRARY_DEFAULT_PATH` assigned as `@ROOT_INSTALL_PREFIX@/@PRIVATE_INSTALLDIR@/$LIB/@CMAKE_SHARED_LIBRARY_PREFIX@exec@CMAKE_SHARED_LIBRARY_SUFFIX@` then. (Note `$LIB` is not expanded. See [`man ld.so`](https://man7.org/linux/man-pages/man8/ld.so.8.html).)

**Comment by morxa** [comment]
> Hey @morxa ,
> 
> Thanks for coming back and give the detailed explanation. I really appreciate it. I was thinking about this change...
> 
>     * I'm planing to merge the `er` and `wrapper` executables into a single one. (Most probably named as `wrapper`.) These shall be out of the regular `PATH` but they are executables. Can live in `/usr/libexec/bear` directory or anywhere else.
> 
>     * The `libexec.so` is a different beast. It's a shared library, which I don't want anybody to link against it.
>       
>       * But there is a ticket to make it work on multilib environment (when it works against 32 bit and 64 bit tools). For that I will need to create two shared libs. And install them as `/usr/lib` (for the 32 bit) and `/usr/lib64` (for the 64 bit) and the `LD_PRELOAD` value will be `/usr/$LIB`. (See [this](https://github.com/rizsotto/Bear/tree/2.4.4#build-with-multiple-architecture-support) for more.)
>       * All these means the `libexec.so` shall be either `/usr/libexec/bear/lib64/libexec.so` and `/usr/libexec/bear/lib/libexec.so` or just fall back to the `/usr/lib64/libexec.so` and `/usr/lib/libexec.so`.
> 
> 
> I'm pretty much convinced that putting these files under an extra `bear` directory is useful. The question is how we do it. Shall the upstream dictate how packages shall be made? I tried to be flexible in the past (means not force things) and let packagers override locations.

That's definitely a good thing, but from my understanding, `CMAKE_INSTALL_LIBEXECDIR` should really point to `/usr/libexec` and not to some package-specifig subdir (otherwise overriding it as packager would actually break things). So yes, overriding the variable would work and not require any changes upstream, but that's not the cleanest way to do it.
> 
>     * So, I would recommend to introduce a variable `PRIVATE_INSTALLDIR` which can have the value `${CMAKE_INSTALL_LIBEXECDIR}/bear`. And use that all around where it need to refer the install location. This can be overridden by packagers if needed.
> 
>     * For `libexec.so` try to introduce the `lib/lib64` directories inside the `PRIVATE_INSTALLDIR`. (Make sure these are not hardcoded, because Debian system has a different convention `lib/i386-linux-gnu` and `lib/x86_64-linux-gnu`)
> 
>     * `config.h.in` shall have `LIBRARY_DEFAULT_PATH` assigned as `@ROOT_INSTALL_PREFIX@/@PRIVATE_INSTALLDIR@/$LIB/@CMAKE_SHARED_LIBRARY_PREFIX@exec@CMAKE_SHARED_LIBRARY_SUFFIX@` then. (Note `$LIB` is not expanded. See [`man ld.so`](https://man7.org/linux/man-pages/man8/ld.so.8.html).)

Yes, a `PRIVATE_INSTALLDIR` makes a lot of sense. I've thought about it, but I didn't want to bring the extra complexity. But I'd be happy to update this PR.

**Comment by rizsotto** [comment]
I saw that similar patch applied to the Fedora package, but the build for this CI fails.

**Comment by morxa** [comment]
Yes, I haven't found the time to fix the CI, but I have it on my list.

I'll ping you when I have it fixed.

**Comment by morxa** [comment]
Hey, I've finally picked it up again and rebased on 3.0.11. Can you let the workflows run so I can see if it still fails?

**Comment by rizsotto** [comment]
Thanks @morxa , I'm glad that you come back to it.

**Comment by morxa** [comment]
Great, thanks for merging!

**Pull request merged**
