### PR TITLE
Correct spelling of BEAR in title

### PR DESCRIPTION
**Pull request by Inventitech**
In addition, the Github repo description reads "Build EAR" (Forks can't modify this)

### CODE REVIEW

**Comment by Godin** [comment]
FWIW looks like duplicate of #220

**Comment by Inventitech** [comment]
I see. The naming Build EAR seems to be confusing ... perhaps 
```
B(uild)EAR 
=========
```

or

```
# Build EAR (BEAR)
=========
```

or
```
# BEAR (Build Ear)
=========
```

would make it clearer?

**Comment by rizsotto** [comment]
Hey @Inventitech , thanks to raise the issue. This project runs since 2012 with the same name, same description in the title. Have a very little feedback on the confusion that the name causes... Please help me to understand the confusion!

To me, it does not matter until I need to rename the repo. :smile: I just need a name for a software. I wish it is unique to find it easy (some distros already have package name collision). And playing with word I find fun... The "Build EAR" is a start of the explanation what the thing is doing.

Do you say, if the document would contain "B(uild)EAR" that would help people to understand what this tool is about or how to use it?

**Comment by Inventitech** [comment]
Hi @rizsotto! 

So, I think it is very clear that the project's name is BEAR and that that should not change and also that the repository should not be renamed.

What confused me (at least) was that it said "EAR" on the title of the Readme. So it seems like a typo.

Now, I also understand why you want to keep the explanation of the name. What I would thus recommend is to simply add its abbreviation in parens after the name -- see the updated PR. 

Thanks :-)

**Comment by rizsotto** [comment]
Thanks!

**Pull request merged**
