### PR TITLE
bugfix: use the correct base directory when reading a -filelist

### PR DESCRIPTION
**Pull request by smoofra**

### CODE REVIEW

**Comment by rizsotto** [comment]
thanks Lawrence, this is really good. but before i merge it, could you provide some small example/test where i can see it was broken before, and now it works fine? i meant a small shell script which use the `-filelist` parameter of Clang.

```shell
$ mkdir build && cd build
$ touch file1.c file2.c file3.c
$ cat files << EOF
./file1.c
./file2.c
./file3.c
EOF
$ clang -filelist files
```

like this, but not sure it is the correct usage. (never seen projects which were using this option.)

**Comment by smoofra** [comment]
Sure.  It’s actually a passthrough option to the apple linker.

set -e 
mkdir example
cd example
echo "int main() { return 0; }" > foo.c
echo "" > bar.c
clang -c foo.c
clang -c bar.c
echo bar.o >files
clang foo.o -filelist files -o foo

bear should say

bear: [Errno 2] No such file or directory: ‘files'

and produce an empty compilation database.

**Comment by rizsotto** [comment]
thank you! still travelling and have little time to work on it. but will merge because it looks good. thanks!

**Comment by rizsotto** [comment]
closing this because it's obsolete. new version will not distinguish between accepted parameters. and `-filelist` belongs to linker phase therefore it would be ignored anyway.

**Pull request closed without merging**
