### PR TITLE
include major version in SONAME of libear

### PR DESCRIPTION
**Pull request by morxa**
Including the major version in the SONAME is good practice to avoid
that the dynamic linker loads a wrong version of the library.

### CODE REVIEW

**Comment by rizsotto** [comment]
Thanks Till, I might be wrong but SONAME is not doing much for preloaded libraries. Nobody shall link against `libear.so` so, the dynamic linker will load the one it finds first in the `LD_PRELOAD` env. (Which is secured by the Bear executable that it will be the first entry.) Or am I missing something?

**Comment by morxa** [comment]
No, it really doesn't do much for preloaded libraries, but it also doesn't do any damage. When installing the lib to /usr/lib, it's good to have a proper SONAME, even if linking against the library is not intended.

I'm working on a Fedora package for Bear, and there it's actually required to have proper SONAMEs when installing to /usr/lib. Alternatively, I could install it to a different location, but I figured setting the SONAME is the easiest way.

**Comment by rizsotto** [comment]
Well, understand the constraints. If I would package this program, I would hide the preload library somewhere `/usr/share/Bear` (or `/usr/share/bear` depending the rules). It would prevent people to link against it by accident

It is unrelated to this, but curious: will you create both 64 and 32bit packages for Fedora? In the README file there is some details how-to for support both with one installation.

**Comment by morxa** [comment]
I haven't included multilib support, but the instructions look like this would be easy to do.

The right location would probably be `/usr/lib/bear/libear.so` and `/usr/lib64/bear/libear.so`. I'll adapt my package accordingly. Maybe this should also be done upstream as you do not want to ever install to the standard library path, if I understand you correctly?

**Comment by rizsotto** [comment]
Thanks for the idea! Changed the install path to `${CMAKE_INSTALL_LIBDIR}/bear`. Will be released in 2.3.11

**Pull request closed without merging**
