### PR TITLE
include terminating \0 in length of argument string

### LINKED ISSUE #160: `bear_encode_json_string` chokes on zero-length strings
I hit a weird bug while trying to get `bear` and `rtags` to play nicely with the linux kernel. The issue lies in `bear_encode_json_string` -- with a zero-length argument, the function incorrectly signals an error and results in the following message:

```
$ bear ./wrapper.sh "" hello_world.c
bear: writing json problem: Success
```

See below for the files necessary to reproduce.

---

**wrapper.sh**
```sh
#!/usr/bin/env sh
shift
gcc $@
```

**hello_world.c**
```c
#include<stdio.h>

int main(int argc, char *argv) {
    printf("Hello World\n");
}
```

### PR DESCRIPTION
**Pull request by jaelsasser**
Fixes #160.

### CODE REVIEW

**Comment by rizsotto** [comment]
Thanks for the PR. I'm hesitant to merge it, for two reasons. Not convinced that +1 will do anything regard to the problem. And would add fixes only with tests... So, if you add those source file and build command to the lit test cases, we would see that the test actually fixes it... If you don't want to familiarized yourself with the test env, (I can understand that) I will do it some day next week.

**Comment by jaelsasser** [comment]
I've done some ad-hoc testing on my local machine with this patch and it resolves the issue, but you're right, there should be some tests attached to this. If I have some time tomorrow I'll try and figure out the test suite.

Thanks for such a useful tool!

**Comment by rizsotto** [comment]
I'm closing this pull request, because fixed this problem in 2.3.5. Thanks for the idea where to look!

**Comment by jaelsasser** [comment]
Awesome, thanks for fixing this! Should make Bear work a lot better with kbuild.

**Pull request closed without merging**
