### PR TITLE
Also include .C, .s, .S and .asm file extensions

### PR DESCRIPTION
**Pull request by RichardsonAlex**
.C is sometimes use for C++ code and the others are assembly language inputs

### CODE REVIEW

**Comment by rizsotto** [comment]
thanks Alexander for this. can you provide an example project when assembly source file counts as source file for Clang compiler? (I'm questioning to add the .s and .asm extension here.) and i think no need to add .C because of the `lower` method call on the extension input. (but correct me if i'm wrong and you actually found a project when .C extensions were not captured in the output.)

**Comment by RichardsonAlex** [comment]
I am building kernel code where the .S files are being compiled (and preprocessed) with clang -x assembler-with-cpp.

I missed the lower() so yes there is no need to add .C

**Comment by rizsotto** [comment]
thanks for the explanation Alex. i'm still hesitant to add those extensions. because i'm still missing the point why shall we record such compiler call into the compilation database? compilation database is for Clang related tools. will any of those tools do anything with such calls? i also ignore preprocessor calls and linker calls, because it is about C/C++ source code compilations. it's not the list of what compiler calls were made. do you know any use-case when you use Clang (or any tools) to do something with these files?

**Comment by RichardsonAlex** [comment]
I am trying to get a browsable version of our source code using https://github.com/woboq/woboq_codebrowser/ and if I don't include the assembly source files in the compilation database any functions that are declared in assembly sources will not be cross-refereced properly.

If you think this might break any existing use-cases of bear I'm happy to submit a patch that makes it opt-in using e.g. --include-asm-sources.

**Comment by rizsotto** [comment]
let me ask on Clang mailing list about it... and yes, we can add extra flag to work around it.

**Comment by rizsotto** [comment]
hey Alex, so i was asking the Clang tooling infrastructure authors on the mailing list. and their current view is that .s and .asm files can be part of the compilation database. (always learning new things :))
also checked the gcc manual and assembly source files has the following extensions: .s, .S, .sx and of course .asm is very common extension too
so, if you can resend the PR with these i would happy to merge it. thanks for your patience!

**Comment by RichardsonAlex** [comment]
Tanks, I've updated the PR, but I'm not sure github notified you.

**Comment by rizsotto** [comment]
thanks Alex, merged to 'devel' branch. will be released next year.

**Pull request closed without merging**
