### PR TITLE
Unify utilities into bear program as subcommands

### PR DESCRIPTION
**Pull request by samu698**
Fix for #412

This PR is still a work in progress.
Here is a tasklist:

- [x] Move bear application code to separate compilation unit
- [x] Move all argument parsing to bear
- [x] Add entry point for subcommands
- [x] Make bear call the right code when issued a subcommand
- [x] Make bear launch the right commands when executing
- [x] Fix the tests
- [x] Edit man pages

### CODE REVIEW

**Comment by samu698** [comment]
While debugging the tests I discovered a problem, after you run `make` for the first time and running `make` again the tests related to intercept will fail, even if you run `make clean` in between.
This is probably because the files generated during the first test don't get removed for the next test.
This can be fixed by removing the directory `subprojects/Build/BearTest/cases/intercept`.

**Comment by rizsotto** [comment]
Thanks @samu698 for making this pull request!

I've found a few references left to the `intercept` and `citnames` programs in the `bear` man file. Will update those myself. The wiki also needs some refresh (after this is released). But had no issues with the code changes.

Excellent work, thanks again!

**Comment by samu698** [comment]
Hello @rizsotto.
Now that all the utilities are merged into one, bear doesn't need to execute commands to run the utilities, it can call the code directly.
This requires a bit of plumbing to pass the right arguments, to the subcommands, but it removes useless expensive executions.
What do you think about it?

**Comment by rizsotto** [comment]
Yes, that could be a next step.

Shall we discuss that in another issue or PR?

**Pull request merged**
